// Generated by build script, do not edit!
// This file is generated for the sole purpose of being included in Windows resource (.rc) files.
// DO NOT INCLUDE THIS FILE IN C++ CODE. Use #include "Runtime/Utilities/UnityConfiguration.h" instead.
#define UNITY_VERSION_BLD 14383776
#define UNITY_VERSION_UNDER_HASH "6000.1.14f1_db7aa045cc2c"
#define UNITY_VERSION_PARENS_HASH "6000.1.14f1 (db7aa045cc2c)"
#define UNITY_VERSION_WIN "6000.1.14.14383776"
